using System.Runtime.InteropServices.JavaScript;
using Bee.UI.Core;

namespace Bee.Northwind.Browser.Storage;

/// <summary>
/// <see cref="IEndpointStorage"/> implementation backed by the browser's
/// <c>window.localStorage</c>. The browser (WASM) sandbox cannot write to the file system,
/// so the file-backed <c>FileEndpointStorage</c> used by the desktop head does not apply;
/// this persists the endpoint under a per-app localStorage key instead.
/// </summary>
/// <remarks>
/// Hosts opt in by assigning
/// <c>ClientInfo.EndpointStorage = new BrowserLocalStorageEndpointStorage("Bee.Northwind");</c>
/// in the head's <c>Program.Main</c>, before any code calls
/// <see cref="ClientInfo.InitializeAsync(string)"/> or <see cref="ClientInfo.SetEndpointAsync(string)"/>.
/// <para>
/// Mirroring <c>FileEndpointStorage</c>, <see cref="SetEndpoint"/> mutates an in-memory cache
/// only; the localStorage entry is written solely by <see cref="SaveEndpoint"/> so a bound
/// input does not hit the JS boundary on every keystroke.
/// </para>
/// </remarks>
public sealed class BrowserLocalStorageEndpointStorage : IEndpointStorage
{
    private const string KeyPrefix = "Bee.Endpoint.";
    private readonly string _key;
    private string? _cachedEndpoint;

    /// <summary>
    /// Initializes a new instance of <see cref="BrowserLocalStorageEndpointStorage"/>.
    /// </summary>
    /// <param name="appName">
    /// Application name used to namespace the localStorage key. Must not be null or whitespace.
    /// </param>
    public BrowserLocalStorageEndpointStorage(string appName)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(appName);
        _key = KeyPrefix + appName;
    }

    /// <inheritdoc/>
    public string LoadEndpoint()
    {
        _cachedEndpoint ??= LocalStorageInterop.GetItem(_key) ?? string.Empty;
        return _cachedEndpoint;
    }

    /// <inheritdoc/>
    public void SetEndpoint(string endpoint)
    {
        _cachedEndpoint = endpoint;
    }

    /// <inheritdoc/>
    public void SaveEndpoint(string endpoint)
    {
        _cachedEndpoint = endpoint;
        LocalStorageInterop.SetItem(_key, endpoint);
    }
}

/// <summary>
/// Minimal JS interop binding to <c>window.localStorage</c> get / set, generated by the
/// browser-wasm <c>[JSImport]</c> source generator.
/// </summary>
internal static partial class LocalStorageInterop
{
    [JSImport("globalThis.localStorage.getItem")]
    internal static partial string? GetItem(string key);

    [JSImport("globalThis.localStorage.setItem")]
    internal static partial void SetItem(string key, string value);
}
